### ISSUE TITLE
你好校友, 能认识一下吗~

### ISSUE THREAD

**Issue by icepie** [nanzhinanzhi/autoup#2]
我之前也写了个同类软件[lit-ncov-report](https://github.com/icepie/lit-ncov-report)

很开心越来越多同学用上了github~, 希望能和你做个朋友. 
 以下是我的联系方式:
```
qq: 1219994313
tg: icepie
mail: icepie.dev@gmail.com
```

**Comment by nanzhinanzhi** [comment]
我加你了
