### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by zrdrz** [nanzhinanzhi/autoup#3]
```
请求失败
Traceback (most recent call last):
  File "/home/zrdrz/autoup/up.py", line 187, in <module>
    upload()
  File "/home/zrdrz/autoup/up.py", line 89, in upload
    s = gettoken(data)
  File "/home/zrdrz/autoup/up.py", line 38, in gettoken
    return s
UnboundLocalError: local variable 's' referenced before assignment
```
卒

**Comment by nanzhinanzhi** [comment]
请检查gettoken(data):方法中使用的loginurl，headers，data

**Comment by nanzhinanzhi** [comment]
请提供一下qq号，我帮你看看，这个issue看着难受

**Comment by zrdrz** [comment]
抱歉，我在issue上提供的信息太少了。我是按readme改好后，在本地运行无异常。试图在 `https://www.pythonanywhere.com/` 这个网站上设个定时启动。试了一次结果这个网站上运行不了，报错信息就是issue上的那段。那网站最低档是免费的，你可以试试，看看问题是啥。看着难受的话，我现在关闭吧^_^。QQ号怕学校天罚不敢在这贴，还有需要的话，可以发我QQ邮箱，`zrd2000@vip.qq.com`。
